<?php

/**
 * ProcessWire Configuration File
 *
 * Site-specific configuration for ProcessWire.
 * This config.php file was generated by the ProcessExportProfile module. 
 *
 * Please see the file /wire/config.php which contains all configuration options you may
 * specify here. Simply copy any of the configuration options from that file and paste
 * them into this file in order to modify them.
 *
 * ProcessWire 
 * Copyright (C) 2017 by Ryan Cramer
 * Licensed under MPL 2.0
 *
 * https://processwire.com
 *
 */

if(!defined("PROCESSWIRE")) die();

/*** SITE CONFIG *************************************************************************/

/**
 * Enable debug mode?
 *
 * Debug mode causes additional info to appear for use during dev and debugging.
 * This is almost always recommended for sites in development. However, you should
 * always have this disabled for live/production sites.
 *
 * @var bool
 *
 */
$config->debug = false;

$config->useFunctionsAPI = true; 
$config->sessionFingerprint = true; 
$config->prependTemplateFile = '_init.php';
$config->appendTemplateFile = '_main.php';
/*
$config->imageSizerOptions = array(
        'upscaling' => true, // upscale if necessary to reach target size?
        'cropping' => true, // crop if necessary to reach target size?
        'autoRotation' => true, // automatically correct orientation?
        'interlace' => false, // use interlaced JPEGs by default? (recommended)
        'sharpening' => 'soft', // sharpening: none | soft | medium | strong
        'quality' => 90, // quality: 1-100 where higher is better but bigger
        'hidpiQuality' => 60, // Same as above quality setting, but specific to hidpi images
        'defaultGamma' => 2.0, // defaultGamma: 0.5 to 4.0 or -1 to disable gamma correction (default=2.0)
        'webpAdd' => false, // set this to true, if the imagesizer engines should create a Webp copy with every (new) image variation
        );
*/
$config->imageSizerOptions = array(
	'upscaling' => false,
	'cropping' => true, 
	'quality' => 90,
	'sharpening' => 'medium',
	);

/**
 * Group items list by object
 */
$config->groupListItemBy = ['duty','brand'];

/*** INSTALLER CONFIG ********************************************************************/



/**
 * Installer: Database Configuration
 * 
 */
$config->dbHost = '127.0.0.1';
$config->dbName = 'cms-pw-sh';
$config->dbUser = 'processwire';
$config->dbPass = 'processwire';
$config->dbPort = '3306';

/**
 * Installer: User Authentication Salt 
 * 
 * Must be retained if you migrate your site from one server to another
 * 
 */
$config->userAuthSalt = 'b1914037413be6d49f629f8089b0d677'; 

/**
 * Installer: File Permission Configuration
 * 
 */
$config->chmodDir = '0755'; // permission for directories created by ProcessWire
$config->chmodFile = '0644'; // permission for files created by ProcessWire 

/**
 * Installer: Time zone setting
 * 
 */
$config->timezone = 'Europe/Stockholm';

/**
 * Installer: Admin theme
 * 
 */
$config->defaultAdminTheme = 'AdminThemeUikit';

/**
 * Installer: Unix timestamp of date/time installed
 * 
 * This is used to detect which when certain behaviors must be backwards compatible.
 * Please leave this value as-is.
 * 
 */
$config->installed = 1595576069;


/**
 * Installer: HTTP Hosts Whitelist
 * 
 */
$config->httpHosts = ['192.168.68.108','localhost'];
